### ISSUE TITLE
./enclavectl build --image kms error

### ISSUE THREAD

**Issue by haozhiyu** [aws/aws-nitro-enclaves-with-k8s#30]
Hi, IHAC who is building the kms image ans is facing a rustc version error as the snapshot attached.Looks like we need to update it too.
![image](https://github.com/aws/aws-nitro-enclaves-with-k8s/assets/48579484/765e5f69-6902-4fc3-8082-e322e8462d5f)

**Comment by dpdornseifer** [comment]
You should update the `kmstool-enclave-cli` binary version to `0.4.1` to get the rust toolchain issue resolved. (https://github.com/aws/aws-nitro-enclaves-sdk-c/tree/v0.4.1)
