### ISSUE TITLE
1.22 is no longer supported

### ISSUE THREAD

**Issue by Xavina** [aws/aws-nitro-enclaves-with-k8s#33]
Hi!

So, this repo is 2 years old now, and looks like the used Kubernetes version is not supported any more:

`Error: invalid version, 1.22 is no longer supported, supported values: 1.23, 1.24, 1.25, 1.26, 1.27, 1.28, 1.29
see also: https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html`

The link -> [EKS Kubernetes verions](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html)

Any plan to update the repo?

I am working on building an EKS cluster that supports Nitro Enclaves, and it's being a hard thing, this documentation is also outdated:

[Using Enclaves with Amazon EKS](https://docs.aws.amazon.com/enclaves/latest/user/kubernetes.html)

I am hacking here and there to make it work, the question is: is there any plan to update the documentation and the repo? Any roadmap? Is AWS still willing to support this technology?

Thanks!

**Comment by meerd** [comment]
Hi @Xavina:

Thank you for your interest in the project. You are right. The repository was created two years ago and needs to be updated. We are still committed to this project and plan to update it within the next few months.
